name: test_deep

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - k
  pull_request:
    branches:
      - k
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**requirements.txt') }}


    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r  requirements.txt
           conda list
           pip list
      
      
    - name: Install dev requirements  
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r  requirements_dev.txt
        conda list
        pip list


        
    - name: Package pip install -e .
      run: |
          mkdir -p    /home/runner/work/log_tmp/
          pip install -e .
          chmod -R 777 . 
          


    ########  Runs CLI checks
    - name: run CLI checks- generate-phone-numbers - 100
      run: |
          generate-phone-numbers    --num_images 100  --min_spacing 1  --max_spacing 7 --image_width 300  --output_path ztmpp/phone1/  --config_file default



    - name: run CLI checks- generate-phone-numbers - 1k
      run: |
          generate-phone-numbers    --num_images 1000  --min_spacing 10  --max_spacing 11 --image_width 400  --output_path ztmpp/phone2/  --config_file default



    - name: run CLI checks- generate-phone-numbers - 10k
      run: |
          generate-phone-numbers    --num_images 10000  --min_spacing 9  --max_spacing 9 --image_width 400  --output_path ztmpp/phone3/  --config_file default



    - name: run CLI checks- Validate Output
      run: |
          validate-phone-numbers    --min_spacing 1   --max_spacing 7  --image_width 300  --input_path ztmpp/phone1/  --config_file default

          validate-phone-numbers    --min_spacing 10  --max_spacing 11 --image_width 400  --input_path ztmpp/phone2/  --config_file default

          validate-phone-numbers    --min_spacing 9   --max_spacing 9  --image_width 400  --input_path ztmpp/phone3/  --config_file default



