# make it explicit that we favor the new container-based travis workers
# https://travis-ci.com/arita37/a_aapackage
# '/home/travis/build/arita37/a_aapackage/batch/ztest/logfile_batchdaemon_monitor.log'

sudo: false

language: python

cache:
  bundler: true
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/miniconda
  - $HOME/download

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/sklearn
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - DISTRIB="ubuntu" PYTHON_VERSION="3.5"
    - NUMPY_VERSION="1.11.0"
    - SCIPY_VERSION="0.17.0"
    - PILLOW_VERSION="4.0.0"
    - JOBLIB_VERSION="0.11"
    - COVERAGE=true
    - SKLEARN_SITE_JOBLIB=1

addons:
  apt:
    packages:
      # these only required by the DISTRIB="ubuntu" builds:
      # - python3-scipy
      # - libatlas3-base
      # - libatlas-base-dev
      # - libatlas-dev



before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
# - ls $HOME/miniconda/bin
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";

  else
    echo "Installing miniconda.";

    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;

    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;


  fi


#### Install conda
install: source zbuild/travis/install.sh


script: 
  # - bash zbuild/travis/test_script.sh
  # - bash zbuild/travis/test_docs.sh
  # - bash zbuild/travis/test_pytest_soft_dependency.sh
  - pip install -e .
  - python ztest/ztest_import.py
  - bash aapackage/batch/ztest/pytest/test_functionnal.sh
  - bash aapackage/batch/ztest/pytest/test_unit.sh
